# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailaddress',
            unique_together=set([('account', 'email')]),
        ),
    ]
